### ISSUE TITLE
Machine name for the settings

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#100]
The ``kinc settings`` command will list all of the settings that are available and their defaults. But it only provides an English version and their values.  If I want to change a setting using the ``kinc settings set`` command I cannot find the machine readable name of the setting.  Can we have this printed out in the help text? Or am I missing something.

**Comment by spficklin** [comment]
Also, there is a new setting 'logging port' that shows up in the GUI but not in the command-line printout.

**Comment by 4ctrl-alt-del** [comment]
I think your missing something with machine readable settings set names...
```
$ aceex help settings set
Command: aceex settings set <key> <value>
Updates a persistent setting with the given key to the new given value.

  key: The key of the setting that will be updated to a new value. Valid keys
       are cuda, opencl, threads, buffer, chunkdir, chunkpre, chunkext, and
       logging.

value: The new value of the given setting.

Help: aceex help settings set <key>
Get help about a specific setting to set with the given key.
```

key: The key of the setting that will be updated to a new value. **Valid keys
       are cuda, opencl, threads, buffer, chunkdir, chunkpre, chunkext, and
       logging.**

**Comment by 4ctrl-alt-del** [comment]
Logging port is indeed missing on command line settings, this will be fixed.

**Comment by spficklin** [comment]
Yes, I missed that thanks...

**Comment by 4ctrl-alt-del** [comment]
Added logging port command line setting in commit d89fcf9da9faffebb2251687b285f026c6c3217d.
