### ISSUE TITLE
Remove OpenCL & OpenMPI requirements

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#13]
In the event that someone doesn't have OpenCL but still wants t use ACE/KINC we should allow them to compile the software without installing OpenCL and in which case only the serial functionality will work.

**Comment by 4ctrl-alt-del** [comment]
This would require a lot of time to implement since OpenCL is so integrated into ACE, probably a couple weeks at least. Will talk to you about it.

**Comment by 4ctrl-alt-del** [comment]
After looking into this I think I could add this to the next minor version of ACE I have just started working on.

**Comment by spficklin** [comment]
Also now we need the ability to compile if OpenMPI is not available either.  I can't compile on windows because OpenMPI is not available for windows.

**Comment by 4ctrl-alt-del** [comment]
...also on my to do list.

**Comment by 4ctrl-alt-del** [comment]
I believe we agreed to abandon this since we want to provide binary versions of KINC for the end user correct?

**Comment by spficklin** [comment]
If we can compile static versions of KINC and distribute those with our releases on GitHub then yes we can drop this.
