### ISSUE TITLE
Command history

### ISSUE THREAD

**Issue by cwytko** [SystemsGenetics/ACE#15]
Within the Console class is there an ability to allocate a buffer (stack) for previous commands and have the ability to re iterate through these commands?
i.e. ACE>blahbah (enter press)
      ACE>              (press up arrow key)
      ACE>blahbah

**Comment by 4ctrl-alt-del** [comment]
We are not doing this due to the fact that we are moving to Qt so this version of ACE is now frozen except for critical bug fixes or updates.
