### ISSUE TITLE
Script to install ACE locally

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#21]
There are many cases where a user might not have root privileges, and so they might have to install ACE locally in order to use it. I generally install software locally anyway when building from source. I came up with a modified version of `install.sh` that does this:

```
set -e

export INSTALL_PREFIX=$HOME/software

rsync -a ./build/libs/ $INSTALL_PREFIX/lib/
rsync -a --include="core/" --include="/console" --include="/gui" --include="*.h" --exclude="*" ./src/ $INSTALL_PREFIX/include/ace/
```

Essentially the same thing as `install.sh` but with an option for the install prefix, so you could do `/usr/local` for a global install, or something like `$HOME/software` for a local install. For a local install you just append these lines to `~/.bashrc`:

```
export INSTALL_PREFIX=$HOME/software
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$INSTALL_PREFIX/include
export LIBRARY_PATH=$LIBRARY_PATH:$INSTALL_PREFIX/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INSTALL_PREFIX/lib
```

And your ACE installation should work just as it would normally. Think it would be worth having in the repo?

**Comment by 4ctrl-alt-del** [comment]
Yes that is a wonderful addition to that script feel free to push it to
develop branch.

Josh

**Comment by bentsherman** [comment]
I actually don't have push access so you'll have to either add it yourself or add me as a collaborator.

**Comment by 4ctrl-alt-del** [comment]
Just added you as collaborator. Again please only push to develop. As far
as coding standards I am very loose except a few things:

1. Declaration of namespaces/types/classes/enumerations are first uppercase
CamelCase and should be a noun/object
2. variable and function names are first lowercase camelCase and should be
verb/action
3. brackets are ALWAYS on their own line
4. if/for/while control structures ALWAYS have brackets even if it is one
line
5. inline commenting of functions is a must, leaving a blank line before
comments unless it is a bracket line
6. NEVER EVER EVER EVER EVER use acronyms or shortened names,
iDontCareIfTheVariableNameTakesAnEntireLineAtLeastIKnowWhatItIsFor :))

That's about it, happy coding!

Josh

**Comment by bentsherman** [comment]
Sounds good, thanks!
