### ISSUE TITLE
Example program hangs when using ACE console

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#26]
I'm trying to test the new MPI functionality but when I run the example program with ACE console, it seems to hang instead of processing command line arguments. In particular, it hangs in `main.cpp:33`:
```
   return application.exec();
```

But when I set a breakpoint on that function call, it still hangs. @4ctrl-alt-del were you able to run the example program without this issue?

I think it's hanging on `QCoreApplication::exec`, like in an event loop...

**Comment by 4ctrl-alt-del** [comment]
I thought I tested the example program with MPI on my machine and it worked, but obviously I missed something huge or there is something special with the openmpi my machine has.

Right now I am in the middle of overhauling the metadata system and need to finish that before I can do anything else as the build for ACE will be broken until that is done. However given this bug along with the continued CCM bug I think I will devote all my time to solve both of these once I am done with the metadata overhaul.

**Comment by bentsherman** [comment]
When you do get to this issue, another related issue that I've encountered is in `EApplication::run`:
```
   connect(analytic.get(),SIGNAL(exceptionThrown(QString,int,QString,QString,QString)),this
           ,SLOT(exceptionThrown(QString,int,QString,QString,QString)));
   connect(analytic.get(),SIGNAL(finished()),this,SLOT(finished()));
```

Because these statements happen outside of the block before it, `analytic` is null at this point for all slave nodes so their signals aren't connected properly. I can work around this myself for now though.

**Comment by bentsherman** [comment]
This one was on me... I forgot to update the headers in `main.cpp` so it was using the ACE GUI header even in the console mode. Pushed the fix to `mpi-hacks`, however I'll wait until we merge `cuda-support` to change the MPI code in the example analytic.
