### ISSUE TITLE
MPI considerations

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#27]
I've been documenting the issues / considerations that I've come across while implementing MPI functionality. I think I'm just going to aggregate them here in a list so that @4ctrl-alt-del doesn't go insane (sorry if I've been flooding your email).

- Input arguments (including data objects) should be available to slave nodes so that the master doesn't have to send them everything (and it will make code re-use much more viable).
- Related to the previous item, some `connect` calls fail in `EApplication::run()` because `analytic` is not set for the slave nodes.
- The MPI framework should be able to handle the use case where each slave node processes a single block. This seems to work but may require some additional code.
- The MPI framework should allow the master node to defer incoming result blocks if they are out of order. I think this behavior was implemented in `EAbstractAnalytic::processMPI()`, but since `processMPI()` is only called when data is received, the master will hang if all blocks have been received but some were deferred. So we need another way to trigger `processMPI()`, perhaps through `QMPI::timerEvent()`?
- `QMPI::shutdown()` must be called by __all MPI processes__ at the end (whether successful or not) in order for the program to terminate. Otherwise it will still work but it will hang at the end.

Regarding the first two items, I have worked around them for now by moving code out of the `mpi.isMaster()` check.

I have also been able to do block-level decomposition without much issue, but we may need a way for the slave nodes to notify the master of their progress so that the master can update it's progress bar.

**Comment by bentsherman** [comment]
A related issue is how MPI blocks are distributed by the master node. Based on the example application, it seems like the master node packages each element-wise operation into an MPI block. However, this technique will not scale due to the large amount of communication required.

What I intend to do in the KINC analytics is to perform block-level decomposition: the master node sends an index to each slave node (or better yet, the slave node determines it's index from it's MPI rank), the slave node computes a block of gene pairs, sends the results in bulk to the master node, and the master node saves the results from each block to the output.

So far it seems like I can still do this through the current API, but since the example is done differently I wasn't sure whether or not this use case will work with the ACE back-end as it is currently written.

**Comment by bentsherman** [comment]
Regarding my previous comment, I think I've been able to implement block-level decomposition without issue. However, KINC hangs once all of the blocks are finished, and I think it's because `MPI_Finalize()` is never called. So `QMPI::shutdown()` needs to be called at the end __by all processes__, and then the main process should exit.

**Comment by 4ctrl-alt-del** [comment]
I agree with all your points. Fixing MPI is top priority for me and I would be doing it right now if I wasn't in the middle of refactoring the metadata system. I have to finish that now because ACE is now broken and doesn't compile until the new metadata system is up and running.

You have one point incorrect; For deferring results, internally ACE keeps a buffer of all received blocks and will keep calling processMPI, cycling through all the buffered blocks, until all of them have been processed. So there should be no hanging there :)

Aside from that all your other points are spot on. No worries about flooding me with issues, I appreciate the help :)

**Comment by 4ctrl-alt-del** [comment]
Actually, nevermind, you are correct it will hang due to deferrment because that was implemented incorrectly too :/

**Comment by bentsherman** [comment]
Awesome! And for what it's worth, this is my quick 'n dirty fix for the deferment issue while I'm developing KINC:
```
      else
      {
         QTimer::singleShot(1000, this, SLOT(processMPI()));
         break;
      }
```

**Comment by bentsherman** [comment]
So I was able to add MPI support to the GMM analytic, and for now it should work if you use the `mpi-hacks` branch. The thing is that `GMM::processMPIBlock()` is essentially a re-implementation of `EAbstractAnalytic::run()` with some extra MPI code. It's not an issue, I mean everything works fine and we could leave it this way, but for the future, maybe there's a way to bake the MPI behavior a bit more directly into `EAbstractAnalytic::run()`. The slave nodes can handle some MPI details directly in `runSerial()` and `runBlock()`, which you can see in the GMM analytic, __if they can determine their piece of work solely from their rank__. Then all you need is a method for the slave node to initialize a few variables and `readMPIBlock()` to aggregate the data on the master node.

I think there is a point of contention here: do you have the slave node determine it's piece of work from it's rank, or do you have it wait for work packages from the master? Your API is geared towards the latter and works with the former with some hacking, but I'm wondering if the latter is a worthy-enough use case to support. On the one hand, if every slave could just use it's rank then it would be very easy to bake MPI behavior elegantly into existing code. But there may be some use case where work packages are better because of load balancing or something, I don't know. Either way, everything works as is so not a pressing issue.

**Comment by 4ctrl-alt-del** [comment]
I completely agree with your recommendations. When I fix MPI, which will be much easier thanks to you, I will make it centered around the slaves determining their work on their own. So the slaves will be process driven simply chomping through their data as fast as possible and sending out MPI bocks. The master will be event driven processing and ordering the blocks from the slaves as needed.

**Comment by bentsherman** [comment]
Well this last part may warrant some more thought. After running a 1200-node MPI job on Palmetto to compute a CCM for GTEX_C2 (roughly 56,000 genes), I noticed two issues:
1. The progression of each node varied wildly.  Since the hardware was pretty uniform, I assume it was because some nodes were able to skip many more gene pairs than others and so they finished sooner.
2. The master node ran out of memory towards the end, which caused the job to fail. Since the slaves wait until the end to send all of their data, I assume the master got overwhelmed by MPI blocks at the end.

So at the very least it seems like the slaves need a way to send intermediate data as they work so that the master doesn't sit around the whole time and then get overwhelmed at the end. And that should be feasible under the new scheme.

But it would be even better if on top of that, the slaves could take on additional work if they finish early, and I'm not sure how we would do that outside of using the current API... so something to think about before we scrap the current API entirely.

**Comment by bentsherman** [comment]
Honestly this could be an experiment in itself: have the master send work blocks that specify (1) the starting gene pair index and (2) the number of gene pair indices to process (some constant called `MPI_BLOCK_SIZE`), and then measure the total runtime as well as the load balance for several values of `MPI_BLOCK_SIZE`.

**Comment by bentsherman** [comment]
Okay here is a solution that might give us the best of both worlds:
1. The master node determines the total number of "steps" (provided by analytic like GMM) and a reasonable MPI block size (probably from constant but in the future could be adaptive (oh man!))
2. The master distributes work blocks to the slaves -- not all of the blocks, maybe like half of them -- and waits for results
3. Every time the master node receives an MPI block from a slave, it subsequently sends another MPI block to the same slave. That way every slave always has a "queue" of MPI blocks which keeps the slave busy, so long as enough MPI blocks are sent out initially.

This setup feels a bit more complex but I think it could be implemented almost entirely in the base analytic class, while also providing performance and load balancing.

**Comment by 4ctrl-alt-del** [comment]
Now that I think about it that was my intent with the current API so this is what I'm going to do;
I'm going to make it so all slave nodes also load any input data and the master node only loads output data. The API will now stay the same and I will add a terminate message to kill all the slaves once the master slave has no more work blocks to send. Now however you should use the work blocks as you said, references to data in the input files the slaves read from.

**Comment by bentsherman** [comment]
Sounds good, I'll update the GMM analytic accordingly. And if you can find a way for the OpenCL/serial launching code to be reusable, perhaps by allowing `run()` to be called for each MPI block or creating another function for just the launching code, that would be ideal. If you look at `GMM::processMPIBlock()` you can see that I pretty much copied it verbatim.

**Comment by 4ctrl-alt-del** [comment]
OK so Stephen wants me to have a fix to MPI out and released ASAP before I do anything else.

I looks at your mpi-hacks branch, it seems legit at fixing the bugs and and keeping the API how we want it. Also seems like all the slaves load the inputs now correct? If this is the case would you be ok with me releasing the mpi-hacks branch as version 2.1.1 of ACE and you can use that to get KINC ready for the conference paper?

**Comment by 4ctrl-alt-del** [comment]
For the termination code you can just add that to the byte arrays of the master node, so when the slave node gets a block from the master that is flagged as a "you're all done" code the slave will just emit the finished() signal.

**Comment by bentsherman** [comment]
Yeah the `mpi-hacks` branch has everything I need to run MPI, feel free to merge it, but be sure to look over the changes to `run()` carefully, I just kind of moved around what I needed to but make sure it won't potentially break things elsewhere (it hasn't for me).

**Comment by 4ctrl-alt-del** [comment]
Yes I scanned over that line by line to make sure, seems ok to me. So I will merge mpi-hacks to master and make it the first revision for 2.1. Congrats you authored a revision of ACE! :)

**Comment by bentsherman** [comment]
Happy to help. ;)

**Comment by bentsherman** [comment]
Currently running a 1000-node MPI job to compute Yeast CCM and everything seems to be in order. So the current items for future MPI development:
- Add method to EAbstractAnalytic that does the capability selection in `run()` so that the code doesn't have to be copied in every child analytic like GMM
- Implement load balancing for the worker nodes. The master node maintains 8 blocks per worker which keeps the worker queues full, but because round-robin is used, the workers that finish their blocks early just quit even though there is plenty of work left to do! lol so anyway the master node should probably keep a list of worker queue lengths and distribute blocks accordingly
- Add code so that when all blocks have been read, EAbstractAnalytic automatically shuts down the worker nodes. That's another thing that will just be copy & paste for every analytic
- Make only the master node print 100% at the end, right now every worker node prints it too

The MPI interface in it's current state should have everything we need for the paper, but I'd like to have these items taken care of before I add MPI to any of the other analytics since it will be easier to do then.

**Comment by bentsherman** [comment]
The good news: my 1000-node MPI job produced Yeast CCM in little over an hour.

The bad news: the CCM metadata seems to be invalid, I can't open it or dump it. This problem does not occur when I run serial. To replicate this error, use these commands with the current build of KINC:
```
# note: disable opencl capability in gmm.h

# serial
./kinc-cli run gmm --input data/Yeast.emx --output data/Yeast-serial.ccm --maxclus 1

# MPI
mpirun -np 8 ./kinc-cli run gmm --input data/Yeast.emx --output data/Yeast-mpi.ccm --maxclus 1
```

This way the CCM contains only metadata, no cluster data (and it finishes quickly). I think the cause might be somewhere in ACE code, probably when the analytic saves metadata to the CCM. I don't see anything in GMM that could cause this... GMM initializes the CCM in `GMM::initialize()`, which is only called for the master node, and in this test case nothing else is written to the CCM during GMM code.

Maybe it's something in `EAbstractAnalytic::finishRun()`? It looks like that's when the command gets saved.

**Comment by bentsherman** [comment]
Found the culprit, after following a faint suspicion... in pulling all of that code out of the isMaster() check in EApplication, all of the nodes were loading the output data argument, which I assume must have corrupted the data object somehow. Brought the `mpi-hacks` branch back to life with the fixes I added which should resolve this problem. Will try my 1000-node job on Yeast again tomorrow.

**Comment by 4ctrl-alt-del** [comment]
Beat me to it, I found the same problem this morning just as I got an email notification about your message. Hopefully that is the only problem and it works now.

**Comment by bentsherman** [comment]
Yep, that fixed it. If I have time I can go ahead and add some of these other proposed changes on the `mpi-hacks` branch.

**Comment by bentsherman** [comment]
So I was able to implement load balancing and auto-termination, but I can't test it because I ran into the same problem as on the `force-serial` branch: I get a segfault from `~EAbstractAnalytic()`. The common thread between these two cases is that I had to add members to `EAbstractAnalytic` (in this case, a list of worker queues), so it seems like something is clobbering something else... I don't know.

The point is, I can't push these changes until we figure out this problem. @4ctrl-alt-del I think testing the multi-GPU setup on Kamiak still takes priority, but eventually I will need your help in tracking this bug since you know ACE better than I. I won't push these MPI changes because it would break the `mpi-hacks` branch, but you can just try out the `force-serial` branch, it's exactly the same error.

**Comment by bentsherman** [comment]
Actually, I was able to add the auto-termination code to ACE since it doesn't require any class members. Be sure to grab that if you get the latest KINC build.

**Comment by bentsherman** [comment]
Awesome! We may need to assess the number of work blocks that are sent to each worker at the start -- I know that previously it was 8, and I think it's 2 now from looking at the code. There's a trade-off because if you don't send enough then the workers will always spend a little time waiting for a new block, but if you send too many then there may not be enough blocks left to do any load balancing. Do you have any thoughts on that?

In meantime I'll go ahead and close this issue, we can explore this trade-off in the future.
