### ISSUE TITLE
Ability to have optional (file / data) arguments

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#28]
Once things calm down a bit, it would be nice to be able to have optional arguments like for files. For example, the Extract analytic will output a text file and a GraphML file, but in case the user doesn't need the GraphML file they should be able to leave the field blank (or not provide the command line argument). I think the support is almost there, but when I try this in ACE gui I get an error when ACE tries to open a file with empty filename, so maybe just add a check before adding file / data arguments?

**Comment by 4ctrl-alt-del** [comment]
This has now been added :) close?
