### ISSUE TITLE
trouble compiling ACE on mpi-hacks branch

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#29]
When I compile ACE I get the following error:

> mpic++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC ->DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB ->DQT_GUI_LIB -DQT_CORE_LIB -I../../src/example -I. -I../../src -I../../../../qt->5.10.1/5.10.1/gcc_64/include -I../../../../qt-5.10.1/5.10.1/gcc_64/include/QtWidgets ->I../../../../qt-5.10.1/5.10.1/gcc_64/include/QtGui -I../../../../qt->5.10.1/5.10.1/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../../qt->5.10.1/5.10.1/gcc_64/mkspecs/linux-g++ -o main.o ../../src/example/main.cpp
> ../../src/example/main.cpp:6:40: fatal error: ace/console/Application.h: No such file or >directory
>   #include <ace/console/Application.h>

I edited the ../../src/example/main.cpp file and changed the #include directive to remove 'ace' from the path.  Then re-running make finished out the compile successfully.  I did not do this before... @bentsherman it looks as though you made the change to add 'ace' to the path.  Did you need that for compiling on your end?

**Comment by bentsherman** [comment]
Actually, I did that wrong, I should have use relative paths there. I just pushed a fix to `mpi-hacks`, so just clear your edits, pull again, and see if everything builds correctly, I want to make sure that ACE builds out of the box on Kamiak. If it does then I'll close this issue.
```
git checkout src/example/main.cpp
git pull origin mpi-hacks
```

**Comment by spficklin** [comment]
Yep, compiles just fine now.  Thanks.
