### ISSUE TITLE
installation of include files

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#30]
On Kamiak I used the following to install the include files for ACE.  I needed this for compiling KINC. Perhaps we should include a variant of this in the install.sh file:

```
mkdir -p ${INSTALL_PATH}/includes/ace
rsync -av --include='*.h' --include='*/' --exclude='*' ./src/ ${INSTALL_PATH}/includes/ace/
```
Also, the install file needs updating to not assume just installation in the home directory or /usr/local

**Comment by bentsherman** [comment]
As a matter of fact, on the `cuda-support` branch I've removed the `install.sh` in lieu of a Makefile, which handles the build and install (I needed it to handle CUDA code easily), so when we merge that branch I'll make sure that these things are taken care of in the Makefile.

**Comment by 4ctrl-alt-del** [comment]
Yea that install.sh was a quick fix because I know qmake generates makefiles that work with 'make install' I just haven't had time to look at that.

**Comment by spficklin** [comment]
Okay, sounds great.  I'll go ahead and close this, but if you want it open, Ben, to remind you about this please re-open.
