### ISSUE TITLE
Interface for running analytic capabilities (discussion)

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#31]
I've been thinking about what @4ctrl-alt-del said about giving control of the block system to the analytic developer, and I'm beginning to think that would be good. It would make the interface simpler and it would allow ACE to be more generic. Not every user may need the block system, for example, an algorithm which consists of a sequence of BLAS / LAPACK operations.

So the interface that I'm envisioning is a single function `run`:
```
void Analytic::run(quint32 capability)
{
   if ( capability == Capabilities::Serial ) {
      // run serial...
   }
   else if ( capability == Capabilities::OpenCL ) {
      // run opencl...
   }
   else if ( capability == Capabilities::CUDA ) {
      // run cuda...
   }
}
```

`EAbstractAnalytic` will still select an applicable capability so this method can assume that the given capability is valid. It would be helpful to abstract this selection code into a separate method like `EAbstractAnalytic::selectCapability()` so that analytics can use this behavior in MPI methods. On that note, the MPI methods should be able to stay the same; `processMPIBlock()` would just select a capability and run it (using the above two methods) to get the same behavior.

**Comment by 4ctrl-alt-del** [comment]
Good ideas, the API slowly forming in my head is even more unified though. Not ready to talk about it yet but the general idea is to make a unified interface that follows a single pattern but is used for any circumstance. So MPI would be baked into the cake and you wouldn't even know you are or are not using it.

**Comment by 4ctrl-alt-del** [comment]
Also addressed in the new ACE v3. Close?
