### ISSUE TITLE
Use multiple OpenCL command queues

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#32]
As I mentioned in the CUDA support issue, CUDA provides streams for managing concurrent, well, streams of operations (for example, each block in an analytic would have its own CUDA stream). But it looks like the OpenCL framework uses just one command queue per device. This is why I'm not convinced  that we're not seeing any benefit from having multiple OpenCL blocks in an analytic, because each block is using the same command queue. So maybe we should have a `EOpenCLCommandQueue` class which manages a command queue and allows for multiple command queues on a device.

Now I could be wrong on all of this because I'm just using my understanding of CUDA, but in order to overlap kernel execution and memory transfers in CUDA you have to use separate, non-default streams because the default stream does not try to overlap operations. And I believe it is possible to have multiple command queues per device in OpenCL.

**Comment by 4ctrl-alt-del** [comment]
src/opencldevice.cpp:
92:   // create new command queue
93:   *_commandQueueID = clCreateCommandQueue(*_contextID,_deviceID
94:                                           ,CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE,&code);

https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clCreateCommandQueue.html

CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE: Determines whether the commands queued in the command-queue are executed in-order or out-of-order. If set, the commands in the command-queue are executed out-of-order. Otherwise, commands are executed in-order.

**Comment by 4ctrl-alt-del** [comment]
Now that I think about it I suppose that last paragraph is an assumption of mine. Since I am completely overhauling all ACE code right now I could easily change it so each kernel has their own command queue, just in case.

**Comment by bentsherman** [comment]
To clarify on this point, what I imagine is that the user can just create a `EOpenCLCommandQueue`, like programs and kernels, which they are free to use however. So you would grab a device, create a command queue on that device, create your kernels and memory buffers, and then when you enqueue memory transfers and kernel calls, you would provide the command queue (or perhaps grab a "default" command queue instance). So at minimum you would need one queue, but with multiple blocks of execution as in the KINC analytics, each block could have it's own command queue. Furthermore, the block could use this command queue instead of managing a list of events like what the KINC analytics do.

This is the paradigm that I used while making the CUDA interface. The thing is that in CUDA you can wait on a stream, which essentially waits on all of the events in the stream, but I'm not seeing an equivalent "wait" function for OpenCL command queues. I think you could still emulate this behavior by managing a list of OpenCL events in the command queue class.

**Comment by 4ctrl-alt-del** [comment]
The analytic block system I am working on in ACE basically does what you describe. Each block will have its own command queue and only wait for itself. ACE will now handle a lot more of the internals so KINC has to do even less. There will be an EAbstractAnalytic::OpenCL::Block class that will have 4 interface functions:

write - write data to GPU
execute - execute GPU kernels
read - read results from GPU
finish - return results back to ACE

We can talk about this more tomorrow if we have our first meeting then.

**Comment by 4ctrl-alt-del** [comment]
This has also been resolved in the new ACE v3. Perhaps close?
