### ISSUE TITLE
Use MPI local rank to grab different OpenCL / CUDA devices

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#33]
We were talking about the scenario where two MPI workers are on a node that has two GPUs, trying to figure out how to tell one worker to use GPU 0 and the other to use GPU 1. During my time here at GTC I think I found a way to do this elegantly:
```
MPI_Comm comm_local;
MPI_Comm_split_type(MPI_COMM_WORLD, MPI_COMM_TYPE_SHARED, 0, MPI_INFO_NULL, &comm_local);

int rank_local;
MPI_Comm_rank(comm_local, &rank_local);
```

This code essentially allows you to group workers by node (workers that can use shared memory with each other), and get the local rank. So for example with Kamiak, you could provision 10 worker nodes across 5 nodes, and each worker would have a local rank of 0 or 1, so it would just pick GPU 0 or 1 accordingly.

I think we could incorporate this particular code into `QMPI` just in something like `localRank()` and `localSize()`, then the OpenCL / CUDA classes or `EAbstractAnalytic` could use it.

**Comment by 4ctrl-alt-del** [comment]
Great work Ben I will add that to QMPI today, thanks!
