### ISSUE TITLE
Option to not allocate host memory for OpenCL / CUDA buffers

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#35]
Sometimes you need "workspace" memory that will be used on the device but never on the host, which means that the host memory of the `OpenCLBuffer` / `CUDABuffer` isn't needed. For small things it probably doesn't matter, but I imagine that as an application scales to larger data, having that extra host memory might be helpful. I know that with CUDA at least, the host memory can be "pinned" which reduces memory transfer times, but allocating too much pinned memory will degrade overall system performance, so it would be good to have something like an `allocHost` option in the buffer constructor.

**Comment by bentsherman** [comment]
It looks like OpenCL has an equivalent feature as `clEnqueueMapBuffer()`, which allocates pinned host memory. I think that would be a good thing to use for OpenCL buffers. If you want more flexibility we could have an enum like this:
```
enum host_mem_type
{
   NONE, // don't allocate host memory
   PAGEABLE, // use new[] / delete[]
   PINNED // use OpenCL / CUDA functions
}
```

**Comment by 4ctrl-alt-del** [comment]
Thanks for the info. After doing some research myself I found that mapping/unmapping operations are slightly faster then read/write in OpenCL. Because of that when I get to refactoring the Buffer class it will simply use map/unmap functions and never allocate host memory.

**Comment by 4ctrl-alt-del** [comment]
Since this has been added to the new ACE v3 I am working on perhaps this should be closed?
