### ISSUE TITLE
ACE 3.1

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SystemsGenetics/ACE#38]
So this is me just keeping notes on what I would like to add later on...

EPointer: a unique smart pointer class very similar to the std unique pointer class except it is qt object aware; that means only qt objects can be set to this pointer and you can release with a qt object argument to set that as its parent. MOST IMPORTANTLY it will not delete its pointer if it has a parent and it will clear any parent a new pointer you give it may have had.

EAllocator: super fast memory allocator that can be used for blocks since they are created and destroyed all the time. Use an arena style memory allocator so it is super fast(at the cost of each allocation has to be the same size in bytes).

**Comment by spficklin** [comment]
Maybe it would be best to add each of these as separate issues?

**Comment by 4ctrl-alt-del** [comment]
None of these ideas are relevant any longer.
