### ISSUE TITLE
Command-line usage text, support command-line in GUI

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#39]
(At some point) ACE should be able to provide a `help` command which generates help text. If `help` is run by itself then ACE should display all available commands. If `help [command]` is run then ACE should display help text for this command, including a list of arguments with descriptions and possibly a description for the command.

Additionally, the GUI library should also provide the CLI interface, as it is independent of the GUI and requires no extra functionality.

**Comment by 4ctrl-alt-del** [comment]
The help system has been added and resolved.

As far as providing the CLI interface in the GUI, that would actually not be easy. The CLI interface is hardwired to use the standard input and output of the program. I would have to rework a large portion of the CLI code before it would even be compatible with interfacing in the GUI. Also the CLI interface is hardwired to interprent a command from command line arguments, run, and exit. This would require a lot of work to accomplish.

**Comment by bentsherman** [comment]
Yeah I don't even remember why I requrested that feature. But I don't need it anymore...
