### ISSUE TITLE
Analytic GUI doesn't always show default value for combo arguments

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#43]
When a combo argument is defined for an analytic, the analytic dialog always shows the first combo value provided by the `ComboValues` (or I guess now it is `SelectionValues`), even if the default value isn't the first one. As an example, look at KINC Similarity -- you'll notice that BIC is the default Criterion value, even though I specify ICL as the default, because I gave { BIC, ICL } as the list of options. I don't think this is an issue for the CLI but it definitely is for the GUI.

**Comment by 4ctrl-alt-del** [comment]
Also resolved in the past and forgot to close this issue.
