### ISSUE TITLE
Replace IntegerArray with DataFrame

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#44]
As I've been upgrading KINC, the biggest difficulty that I've had has been with the features that aren't used by `IntegerArray` but are needed by KINC data objects, in particular the metadata system and disk I/O. Now I'm already working through these issues, but in the future it might be good for `IntegerArray` to implement these things even if they are trivial, so that there is an explicit example of their usage.

**Comment by bentsherman** [comment]
Also side-note: the MathTransform analytic doesn't verify output argument so not providing the output argument causes a seg-fault.

**Comment by bentsherman** [comment]
Also need to implement QAbstractTableModel.

**Comment by spficklin** [comment]
I'm going through adding labels to issues but I'm not sure how to classify this one. Is it a bug?

**Comment by bentsherman** [comment]
I think the best solution here would be to actually replace IntegerArray with a "DataFrame" as in R or pandas. A DataFrame is just a matrix with row names and column names, it's implementation would be almost identical to ExpressionMatrix. This kind of data object would use all of the features of ACE, such as metadata, and honestly it would be a much better example for scientists since they're used to working with dataframes to represent their datasets.

@4ctrl-alt-del I would be happy to write up an implementation and make a PR for it.

**Comment by spficklin** [comment]
One thing to consider is long-term maintenance of ACE.  We have to expect that @4ctrl-alt-del and @bentsherman will move on one day to bigger and better things!  We need to make sure ACE stays slim and manageable while still providing the features we need without being unwisely to maintain. I'm not sure what it would take to add in a DataFrame but just want to through out this consideration.

**Comment by bentsherman** [comment]
Yeah that's a fair point. I think the DataFrame is probably one of the slimmest examples of a data object that uses all of the features available in ACE. And it's a pretty standard data structure so it might even be directly useful to users of ACE.

**Comment by 4ctrl-alt-del** [comment]
The complexity of a data frame class would only be slightly more than the integer array already there. I think the pros outweigh the cons myself so I am fine with you doing this ben... perhaps we should do this with a pull request? I've never done a pull request before but this would be a good way to learn it.
