### ISSUE TITLE
CLI doesn't apply default arguments

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#47]
As far as I can tell, the CLI doesn't seem to set up default arguments properly. I can see that `AbstractManager` queries them from the analytic, but the helper functions in `Ace::Run` for loading numerical and enum arguments throw an error if the value isn't found in the list of command-line options. So I think those checks just need to be modified somehow so that the default arguments are considered.

This issue might be better to tackle now because Similarity has a _lot_ of default arguments.

**Comment by 4ctrl-alt-del** [comment]
Resolved in hotfix 3ae1df9168bd1b419ec539dd932a6db895d4b41f. This includes the previous hotfix for resolving the makeWorker issue and OpenCL::initialize issue.
