### ISSUE TITLE
initialize() method for EAbstractAnalytic::Serial

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#48]
I think it would be good to have an `initialize()` method for the Serial class, like the OpenCL class, because there may be some initialization for the serial workers, and I don't think that could be handled in the main `initialize()` method because that is only called by the master node (if I recall correctly).

**Comment by 4ctrl-alt-del** [comment]
For the serial class you can simply use its constructor to initialization. The serial class is created after its parent analytic has been given its arguments so that shouldn't be an issue.
