### ISSUE TITLE
Change EAbstractAnalytic::OpenCL::makeWorker() to not be const

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#49]
(This is probably the most specific issue I've ever created.)

Could we make this method not be const? From our conversation yesterday, if I want to give the OpenCL worker a pointer to the OpenCL class then I need to be able to provide `this` as non-const. It would mirror the structure of `makeSerial()` and `makeOpenCL()` in `EAbstractAnalytic`, neither of which are const.

**Comment by 4ctrl-alt-del** [comment]
Very specific. This issue along with the much more pressing issue of the OpenCL::initialize method being called before its parent analytic was given its arguments has hopefully been resolved in the hotfix 445e8878150566432cda7653841adfa72df2b6df.

**Comment by 4ctrl-alt-del** [comment]
Created a new hotfix 3ae1df9168bd1b419ec539dd932a6db895d4b41f. Use this instead of the first as this includes the previous hotfix for resolving the makeWorker issue and OpenCL::initialize issue.
