### ISSUE TITLE
Provide read() / write() for OpenCL Buffer

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#51]
Now that I think I understand this map() / unmap() paradigm for OpenCL buffers, I think we'll want to provide both mechanisms: read() / write() as well as map() / unmap(). They are independent methods and I don't think that one is necessarily better than the other in all cases. This issue is also not pressing, but I think users will expect to have both features in the future.

**Comment by 4ctrl-alt-del** [comment]
Agreed, added to my TODO list. :)

**Comment by 4ctrl-alt-del** [comment]
Added in commit 8d671e5fc5ae7f8307e06be501a7d8ffaff87a81. Since you requested this Ben I will let you review the code and close this issue if you are satisfied with it.

**Comment by bentsherman** [comment]
It works! I have some follow-up discussion but this specific issue is taken care of so I'll start a new issue.
