### ISSUE TITLE
Python ACE

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#53]
Just as an item of discussion.  Now that the design for ACE has stabilized.  What would it take to create a Python version?  The reason I ask is because we are creating more and more python based tools and it would really be especially nice to support reading/writing of the data objects with Python.

**Comment by 4ctrl-alt-del** [comment]
From what I can tell after looking it is feasible aka python supports opencl and mpi. What would take the longest is me actually learning python. My knowledge of python stops at a simple hello world script. I would guess it taking me 6-9 months to learn python well enough to attempt this.
