### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#54]
@bentsherman do we need to make any changes to ACE so that you can get performance metrics for your research project?

**Comment by 4ctrl-alt-del** [comment]
Is this something still needed for ACE or should I close it? I did some research and because of Nvidia it is almost impossible to profile OpenCL on any of their hardware because of their open contempt for anything open source.

**Comment by bentsherman** [comment]
Lol. Yeah we don't need this anymore. Now that ACE has CUDA support I can get everything I need through `nvprof` and cuPTI.
