### ISSUE TITLE
Build error on Ubuntu (solved)

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#55]
I figured out what was causing errors for me on Ubuntu: the order of linked libraries. Refer to this answer on StackOverflow:

https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc#409470

According to the answer, libraries with missing symbols should be listed before libraries that resolve those symbols, because the linker scans and resolves from left to right. So for example, `-lacecore` should come before `-lmpi` and `-lOpenCL` or else you get "undefined reference" errors. However, the SO answer also notes that on some distributions you can "get away" with an incorrect order; @4ctrl-alt-del I'm guessing that such is the case for CentOS and Gentoo.

Anyway, I just had to change the library order in `example.pri`:
```
LIBS += -L$${PWD}/../../build/libs -laceexcore -lacecore -lOpenCL -lmpi
equals(MPICXX,"yes") { LIBS += -lmpi_cxx }
```

I've already updated the corresponding issue in KINC.

**Comment by 4ctrl-alt-del** [comment]
Resolved in commit 7ed73f18436c3fcfafe30bac1e730dc97dee0d3f.
