### ISSUE TITLE
MathTransform example doesn't check for required output argument

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#58]
The MathTransform analytic doesn't make sure that `--out` is provided, so if it isn't provided a segfault occurs.

**Comment by spficklin** [comment]
Does this need to be fixed for the v3.0.2 or 3.1 milestones?

**Comment by 4ctrl-alt-del** [comment]
Fixed in commit d47dad9740989c3ab968fab7b0fa9d9f6c147c74.
