### ISSUE TITLE
Disable logging during settings run

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#61]
I think this started happening after the latest release, so when the logging / debugging code was introduced. The logger seems to supersede the settings interface, so even if I try to run "kinc settings set logging off", ACE still waits for a TCP connection for the logger. This behavior is kind of weird to me, I think most users would expect the settings interface to take precedence. So I think the logger should be disabled during a settings run.

**Comment by spficklin** [comment]
Hi Ben, just curious why this got closed?

**Comment by 4ctrl-alt-del** [comment]
Because it only existed in a single commit and was changed the very next commit. Logging only happens when an analytic is ran. I accidently left the log server where it was in the one commit for testing purposes.

**Comment by spficklin** [comment]
Okay, thanks for the clarification.  I just want to make sure we know what the resolution was.
