### ISSUE TITLE
Build the API documentation

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#64]
Prior to our ACE publication which should be based on v3.0.2 we need a site with the API documentation. This coupled with the Class creation doc described in #63 we will have everything needed to help someone create a new ACE-based app.

**Comment by 4ctrl-alt-del** [comment]
Please remind me how we are going to host this site and what its name will be?

**Comment by bentsherman** [comment]
Probably Github pages.

**Comment by 4ctrl-alt-del** [comment]
That was my first thought but when I investigated github pages it mentions nothing about doxygen and from what I can tell only supports markdown text files.

**Comment by bentsherman** [comment]
Well markdown has built-in support for HTML so I think we can just add the HTML files generated by Doxygen and it will work.

**Comment by 4ctrl-alt-del** [comment]
The API documentation is now available at http://systemsgenetics.github.io/ACE/

**Comment by spficklin** [comment]
Wonderful!
