### ISSUE TITLE
Improvements for EDebug

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#66]
Using this issue to document ideas for future improvements of EDebug.

- **More compact output**: print only one line per function call, listing the arguments in the parentheses (as in gdb). EDebug could support both formats and others through an ACE setting
- **Indent size**: ability to change the number of spaces per indent through ACE setting
- **Filtering**: have some built-in way to filter out information. Filters could include namespace, class, function, stack depth, arguments, argument values, etc. Alternatively if you just print one line per function call then you can do all of this after the fact.

**Comment by 4ctrl-alt-del** [comment]
As discussed I have added the ability to whitelist specific source files to actually report from the EDEBUG_FUNC macro. Added in commit 36e537f166e2388b4abc1c75e0366d7cbff2df47 of develop branch. Please let me know if this works.

**Comment by bentsherman** [comment]
I think it works, but it's still printing `lala` instead of the actual line.

**Comment by 4ctrl-alt-del** [comment]
Oops! I forgot to remove the test line I used to make sure it worked for me. Fixed in 3de8b6479f194113834249f52ab987fc1dbdd560. Sorry about that! Let me know if it works properly now.

**Comment by bentsherman** [comment]
It works! Wow this is so much better.

This pretty much takes care of the third item from my OP. I still think the compact output would be very helpful. Here's an example function call currently:
```
int Similarity::Serial::fetchPair(const Pairwise::Index&, QVector<signed char>&)
{
   this = 0x7fd953200ab0(Similarity::Serial)
   &index = 0x7ffd1cb99600
   &labels = 0x7ffd1cb995f0
}
```

My idea of a "compact" output would be something like this:
```
int Similarity::Serial::fetchPair(const Pairwise::Index&, QVector<signed char>&): this = 0x7fd953200ab0(Similarity::Serial), &index = 0x7ffd1cb99600, &labels = 0x7ffd1cb995f0
```

So everything is on one line, and you don't need the brackets because the indentation already informs the scope (like Python lol). This format is much more compact, which might be easier to scroll through and search quickly. This could be enabled by either the `logging` setting or a new setting.
```
kinc settings set logging compact # or on (full), off
```

**Comment by 4ctrl-alt-del** [comment]
Reworked in commit 21bf42de7e29eb9916356d9f4c6d2d1719ebf730. I will let you review the changes and close this if it is satisfactory.

p.s. I also changed the indent width to 4 because that is a commonly accepted standard.

**Comment by bentsherman** [comment]
Looks good to me!
