### ISSUE TITLE
ACE compile error

### ISSUE THREAD

**Issue by mrbende** [SystemsGenetics/ACE#70]
1. I ran these commands and got a compile error for ACE. 
git clone https://github.com/SystemsGenetics/ACE.git
cd ACE/build
qmake ../src/ACE.pro PREFIX=$HOME/software
make qmake_all
make

2. It worked up to this point
mpic++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DMAJOR_VERSION=3 -DMINOR_VERSION=0 -DREVISION=1 -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I../../src/core -I. -isystem /software/Qt/5.9.2/include/QtGui -isystem /software/Qt/5.9.2/include/QtCore -I. -isystem /usr/include/libdrm -I/software/Qt/5.9.2/mkspecs/linux-g++ -o opencl_platform.o ../../src/core/opencl_platform.cpp
In file included from ../../src/core/opencl_platform.cpp:1:
../../src/core/opencl_platform.h:3:10: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [opencl_platform.o] Error 1
make[1]: Leaving directory `/home/mrbende/software/ACE/build/core'
make: *** [sub-core-make_first] Error 2

**Comment by 4ctrl-alt-del** [comment]
That tells me you do not have OpenCL installed on your system. In linux the folder /usr/include/CL, that contains all the OpenCL header files, should exist and within that cl.h should exist.

**Comment by mrbende** [comment]
I do have OpenCL installed on my system, libOpenCL is installed as a dependency and is included in my path. As you mention however, the /include folder is missing a cl.h file. It is possible I have an incompatible version of the cl package installed on my system. The dependencies for ACE are not listed in the usage instructions, so could you direct me to the correct CL installation?

**Comment by mrbende** [comment]
I am using Clemson's Palmetto Cluster, which runs Scientific Linux through PBS. I have attatched a screenshot of the dependencies I have installed. The rest are loaded as modules. Qt works
![capture](https://user-images.githubusercontent.com/43684185/47719182-bfd0da80-dc20-11e8-8685-3a16c45139b8.JPG)

**Comment by 4ctrl-alt-del** [comment]
You will need a module that provides you the header files from OpenCL. The screenshot you provide is just the compiled shared library. For ACE to compile against OpenCL it needs the header files that define it. I'm guessing your OpenCL module is not a development version and does not provide the header files.

I don't use Palmetto nor can I so I have no idea how it works. On kamiak I use the CUDA module that provides the header files. Basically you will have to find a development version of OpenCL, not just a runtime version.

@bentsherman mighty know more since he can use Palmetto.

**Comment by mrbende** [comment]
This is helpful, thank you. I will look for a develop version that provides the .h file necessary, and if I have trouble I will refer to Ben. Much obliged.

**Comment by bentsherman** [comment]
Yeah I completely forgot to provide the Palmetto specific instructions, I'll put them in the README.md of KINC.
