### ISSUE TITLE
Extract analytic gives no progress

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#71]
I ran the extract analytic with on the results generated as described at the end of issue #62 .  I used a cutoff of 0.7 just to test.  It ran for 1 hour 22 minutes but it gave no progress indicator.

**Comment by bentsherman** [comment]
This is actually an issue with KINC, the import/export analytics perform their work in a single "work block", so that the only progress update happens at the end when it's all done. I will update these analytics to break up the work into multiple blocks so that the progress bar works.

**Comment by 4ctrl-alt-del** [comment]
Remember to add a check in initialize() to make sure you are running in single mode and not MPI or chunk mode. Hmm, I need to add a method that tells you that in the analytic class don't I?

**Comment by bentsherman** [comment]
Well I can use initializeOutputs() for the output file, but as long as I don't define a Serial class it shouldn't allow chunkrun or MPI right? If I specify multiple work blocks but only define process() will it just pass the work blocks directly to process()?

**Comment by 4ctrl-alt-del** [comment]
Sorry I was thinking about it the wrong way you are correct. :) Just return a null pointer to make serial and opencl and it will default to a simple run or not run at all if it is MPI or chunk.

**Comment by bentsherman** [comment]
I just added progress bar functionality to ImportExpressionMatrix in the latest KINC commit. The progress bar is pretty smooth, for large matrices it may appear to hang briefly at 99%. I'll go ahead and update the other import/export analytics, let me know how it works for you.

**Comment by spficklin** [comment]
Okay, I can recompile on Kamiak to test. Just to confirm, no changes were made in ACE... just in KINC?

**Comment by bentsherman** [comment]
All of the import/export and extract analytics should have progress bar support, just pull the latest KINC commit. Let me know if it works for you, and also let me know if it takes significantly longer than before.

**Comment by 4ctrl-alt-del** [comment]
@spficklin I tested this myself and the progress bar seems to work now, does it work for you? Can this be closed?

**Comment by spficklin** [comment]
If you tested it and it works, let's close it. If for some weird reason it crops up again we can reopen the issue.
