### ISSUE TITLE
Dynamic input items

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#72]
Is it possible for ACE to support an analytic that has a variable number of input parameters?  For example, say I want to create an analytic for KINC that would calculate condition-specific p-values for each GMM cluster.   Suppose I had 15 conditions then I would generate 15 p-values for each cluster. I would need to then save those p-values in a new data file.    Next say I want to filter the data in that new file such that I extract only p-values below or above a given value.  The input arguments would be different for every file because one file may have 15 conditions and another may have 5, or another 100.   

Could I create an analytic that would allow a set of filters in the QT window that could change depending on what was in the input file?

Maybe the solution isn't a variable number of different arguments but one argument (e..g --p-filter) that I could provide multiple values for?

**Comment by 4ctrl-alt-del** [comment]
ACE does not support a variable number of input parameters.

Your last solution would work, you can surround an input argument with quotes on the command line and separate each argument by spaces as an example.

**Comment by 4ctrl-alt-del** [comment]
I'm going to close this @spficklin because we talked about this in person and said the last solution should work fine.
