### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#75]
So, this is not urgent, but this came up via a Slack conversation between myself and @4ctrl-alt-del.  Inside of a GUI ACE application like KINC there is a File > Settings menu.  All of those settings are currently provided by ACE and they are persistent.   The first for issue #74 will help clarify that for end-users.

However, I can see the case that an ACE app may also want to have settings specific for itself.  So far KINC doesn't. But for the future, perhaps ACE should provide an API such that an app could add it's own persistent settings?

**Comment by 4ctrl-alt-del** [comment]
This would be reinventing the wheel. Qt already provides this with the QSettings class.

**Comment by spficklin** [comment]
Fair enough.  I didn't realize Qt provided this functionality.  I thought it was an ACE construct.
