### ISSUE TITLE
ACE settings run returns non-zero exit code

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#78]
Here's an example command line:
```
$ aceex settings set opencl none
$ echo $?
255
```

I get a non-zero exit code even though the command exited successfully. Normally this doesn't really matter but now that I'm writing a nextflow pipeline for KINC, it does matter because nextflow uses exit codes to determine whether a process failed or not.

I think you just need to change `EApplication::exec()` in ACE console. It looks like the settings run doesn't explicitly return 0 like the other commands, so the function returns -1 at the end.

**Comment by 4ctrl-alt-del** [comment]
Fixed in 3b5c50806c902f5bc99381d9bdae169ec11f8207.
