### ISSUE TITLE
Change organization name to "SystemsGenetics" in ACE example

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#80]
That's what I set it to for KINC, that way their config files will show up in the same folder instead of "Unknown Organization".

**Comment by 4ctrl-alt-del** [comment]
Fixed in 3b5c50806c902f5bc99381d9bdae169ec11f8207.

**Comment by bentsherman** [comment]
I feel like a real stickler for pointing this out... but you made it `SystemGenetics` instead of `SystemsGenetics`.

**Comment by 4ctrl-alt-del** [comment]
Oops :)

**Comment by 4ctrl-alt-del** [comment]
Refixed in 48219954fe92be944a70d07c9e034.
