### ISSUE TITLE
Display runtime and predicted time remaining in ACE CLI

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#81]
I think it would be useful to print timing statistics alongside the percentage progress for the CLI as in the GUI. An example:
```
1%      1h1m    101h40m
```

So alongside the percentage, include the current runtime and the estimated remaining time based on either a simple percentage calculation (runtime * 100 / percentage) or something more sophisticated based on a running average.

**Comment by 4ctrl-alt-del** [comment]
Added in 3b5c50806c902f5bc99381d9bdae169ec11f8207.

**Comment by bentsherman** [comment]
Looks good except for the percent sign is in the wrong spot lol:
```
1	12s	19m48s%
2	25s	20m25s%
3	38s	20m28s%
```

**Comment by 4ctrl-alt-del** [comment]
LOL indeed :)
Apparently my fixes also had lots of typos...

**Comment by 4ctrl-alt-del** [comment]
Refixed in 48219954fe92be944a70d07c9e034.
