### ISSUE TITLE
Bug with selection arguments

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#84]
Found a issue in the code here:

https://github.com/SystemsGenetics/ACE/blame/develop/src/console/ace_run.cpp#L513

Basically this condition should have a `!` negation which was removed recently so now it fails when the input is correct... whoops.

**Comment by 4ctrl-alt-del** [comment]
Fixed in 05f44ba6ccf615706d0b753c2ec8dc551c0c52e0.
