### ISSUE TITLE
Display percentage progress for chunkrun

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#86]
If I recall correctly the `merge` command already displays percentage progress because it uses the same facilities as `run`. If it's not too difficult could we implement this for chunkrun as well? It would be helpful for obvious reasons.

**Comment by 4ctrl-alt-del** [comment]
Added in commit 36e537f166e2388b4abc1c75e0366d7cbff2df47 of develop branch. Please let me know if this works.

**Comment by bentsherman** [comment]
Works great!
