### ISSUE TITLE
chunkrun hangs when _nextWork >= _end

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/ACE#90]
If I try to run the following, it hangs:
```
kinc chunkrun 99 100 similarity --input Yeast.txt
```

The Yeast GEM has 7050 genes, which leads to 759 work blocks for similarity, and with 100 chunks it means that each chunk processes 8 work blocks. But that means that the last few chunks actually have no work blocks to process, and although they should just exit with an empty chunk file, instead they hang.

I traced the cause to the interplay between, at least for the serial run,`Chunk::process()` and `SerialRun::addWork()`. The reason is that `addWork()` checks to see if the chunk is finished, not `process()`, but if there are no blocks to process, then `addWork()` never gets called.

I'm not sure what the exact code changes should be, but basically the `Chunk::process()` method needs to be modified so that it can emit the `finished` signal even if `_runner->addWork()` is never called.

**Comment by 4ctrl-alt-del** [comment]
Possible fix in commit 0c97a69f67f768ed83ec1e9697c58d3c0321ee0b

Please let me know right away if that resolved your issue.

**Comment by bentsherman** [comment]
Fixed! Thanks for the quick response.
