### ISSUE TITLE
About details

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/ACE#95]
We need an "about" dialogue that provides information about the version of the tool, the copyright, license information, authors, etc.  

As a discussion with @4ctrl-alt-del typical software behavior is to put this type of information in an 'About' link under a 'Help' menu item. But since we don't have a help menu for now it could go under the 'File' menu.

**Comment by 4ctrl-alt-del** [comment]
Added in commit 78ac7433e2446b2c94e029ef987393efba5fc0c2.
